### ISSUE TITLE
registerObject() on a non-object

### ISSUE THREAD

**Issue by fightbulc** [Codeception/AspectMock#10]
Hey. Seems not to work at all. I am running PHP54 and AspectMock 0.4.0

I am trying to mock the following:

``` php
$usersCrudManager = new UsersCrudManager();
test::double($usersCrudManager, ['create' => 'test']);
```

When I am running the test with codeception I am receiving the following:

``` bash
FATAL ERROR. TESTS NOT FINISHED.
Call to a member function registerObject() on a non-object
in /Users/fightbulc/www/jobs/piraya/service/vendor/codeception/aspect-mock/src/AspectMock/Core/Registry.php:30
```

I had a look in the code and figured that `self::$mocker` isn't set. Setting it via `Registry::setMocker(new Mocker());` solves the issue from above. However, it still doesn't mock my class.

Also, I didn't see any examples where `Mocker()` needs to be set explicitly.

What needs to be done here, what do I miss?

Cheers
Tino

**Comment by sameg14** [comment]
So what exactly did you do to get this work? I am still having a hard time.

**Comment by fightbulc** [comment]
Hey there. Its been a while but including and adjusting the following file solved my issue:

https://github.com/Codeception/AspectMock/blob/master/tests/_bootstrap.php

**Comment by sameg14** [comment]
Awesome, thanks dude!

**Comment by settermjd** [comment]
Thanks for sharing @fightbulc worked for me as well.

**Comment by besrabasant** [comment]
@fightbulc I am still not able to sort out the problem.
