### ISSUE TITLE
Not work with phpunit 5.4.2

### ISSUE THREAD

**Issue by skibish** [Codeception/AspectMock#103]
Encountered interesting error, that AspectMock not mocks static with phpunit 5.4.2.
Downgraded to phpunit 5.3.5 and everything works good again.

Additional info:
PHP 7.0.6
Xdebug 2.4.0
PHPUnit 5.4.2
AspectMock 1.0.0

**Comment by smoakey** [comment]
Is there a minimum phpunit requirement?
