### ISSUE TITLE
Error while rewriting a BUILT-IN function with args passed by reference

### ISSUE THREAD

**Issue by mpyw** [Codeception/AspectMock#106]
This issue is related to #33 #39, but it's still reproducible on **built-in** functions. If we add the following test, it will be failed.

``` php
    public function testReimplementFuncWithPassedByReference()
    {
        $array = [3, 6, 4, 8, 1, 0];
        test::func('demo', 'sort', function (array &$array) {
            usort($array, function ($x) { return $x - $y; });
        });
        sort($array);
        verify($array)->equals([0, 1, 3, 4, 6, 8]);
    }
```

**Comment by paulgessinger** [comment]
Encountered this problem when trying to mock socket_recv which write results to a reference parameters.

**Comment by bhoehl** [comment]
@DavertMik 
https://github.com/Codeception/AspectMock/blob/master/src/AspectMock/Proxy/InstanceProxy.php
the same issue is happening here when using __call and referenced parameters
In php it is not possible to pass arguments as variadic or using __call and have them be "by reference"
So basically all arguments passed to 
__call($name, $arguments) 
__callStatic(...)
myfunc(...$args)
are none reference ones and it is not possible to call a function below and return the modified value back
The code in InstanceProxy and the one for mocking built in functions both have this issue.
InstanceProxy does not produce an error, but you won´t get back any result.
The only way to "fix" that is to create a new function with the same parameter definition as before not using any func_get_args().
