### ISSUE TITLE
andrewsville/php-token-reflection does not work with modern PHP features

### ISSUE THREAD

**Issue by ramsey** [Codeception/AspectMock#110]
I'm encountering the following problem while attempting to use AspectMock on PHP 5.6. When I run my tests, I get errors on nearly all of them, with messages like this:

```
TokenReflection\Exception\ParseException: Invalid value definition.
```

I've tracked it down to a problem in the [andrewsville/php-token-reflection](https://github.com/Andrewsville/PHP-Token-Reflection) package, where it cannot parse scalar expressions in class constants. Since PHP 5.6+ supports scalar expressions in class constants, and I use them heavily in this code base, AspectMock is broken for me.

The andrewsville/php-token-reflection package has had a pull request open for nearly a year to fix this, but no one has merged it in, and the project appears stale (no updates in 2 years): https://github.com/Andrewsville/PHP-Token-Reflection/pull/72

Has AspectMock considered switching to a different reflection library? Staying with andrewsville/php-token-reflection seems like it will greatly restrict use of AspectMock to those not taking advantage of PHP 5.6+ features.

One potential replacement is [roave/better-reflection](https://github.com/Roave/BetterReflection). cc: @asgrim

I'd be willing to help make the changes to get this working, if interested.

**Comment by lisachenko** [comment]
Hi, @ramsey! Version 2.0 of AspectMock is already using new version of Go! AOP, that capable to handle 5.6 and 7.x versions of PHP. I decided to create a modern reflection library that will be fully compatible with original reflection, so have developed [goaop/parser-reflection](https://github.com/goaop/parser-reflection) library.

Library `andrewsville/php-token-reflection` won't be used anymore.

So, you only need to change AspectMock version in your project to ~2.0 for having PHP5.6+ support.

**Comment by ramsey** [comment]
Thanks for the response. You might want to update your [GitHub releases page](https://github.com/Codeception/AspectMock/releases). It still shows 1.0.0 as the "Latest Release."

I'll update!

**Comment by lisachenko** [comment]
Hey, @DavertMik, consider writing release notes for v2.0.0 ) Because without that newer tags are hidden
