### ISSUE TITLE
Go\ParserReflection classes not loading

### ISSUE THREAD

**Issue by adrian-enspired** [Codeception/AspectMock#112]
I'm using aspect-mock 2.0.0 and it seems that the classes in `Go\ParserReflection` are not being loaded:

```
PHP Fatal error:  Uncaught Error: Class 'Go\ParserReflection\ReflectionFile' not found in {app root dir}/vendor/codeception/aspect-mock/src/AspectMock/Intercept/BeforeMockTransformer.php:16
Stack trace:
#0 {app root dir}/vendor/goaop/framework/src/Instrument/Transformer/CachingTransformer.php(124): AspectMock\Intercept\BeforeMockTransformer->transform(Object(Go\Instrument\Transformer\StreamMetaData))
#1 {app root dir}/vendor/goaop/framework/src/Instrument/Transformer/CachingTransformer.php(83): Go\Instrument\Transformer\CachingTransformer->processTransformers(Object(Go\Instrument\Transformer\StreamMetaData))
#2 {app root dir}/vendor/goaop/framework/src/Instrument/ClassLoading/SourceTransformingLoader.php(134): Go\Instrument\Transformer\CachingTransformer->transform(Object(Go\Instrument\Transformer\StreamMetaData))
#3 {app root dir}/vendor/goaop/framework/src/Instrument/ClassLoading/SourceTransformingLoader.php(101): Go\Instrument\ClassLoading\SourceTransformingLoader::transformCode(Object(Go\Instrument\Transformer\St in {app root dir}/vendor/codeception/aspect-mock/src/AspectMock/Intercept/BeforeMockTransformer.php on line 16
```

The file does exist in `vendor/goaop/parser-reflection/src`.  If I `require` it explicitly, it works, but fails on the next `Go\ParserReflection` file. 

I realize this might be a Composer issue, but everything seems to be set up correctly.  The namespace+path is registered in composer's autoloader.  I've even tried registering it again at runtime:

``` php
$goaop = realpath(__DIR__ . '/../vendor/goaop/parser-reflection/src');
var_dump($goaop); // string(51) "{app root dir}/vendor/goaop/parser-reflection/src"
$autoloader->setPsr4('Go\\ParserReflection\\', $goaop);
```

Google has shown me [one other example of this problem](https://travis-ci.org/dektrium/yii2-user/jobs/140011491#L520), but no indication as to how/if it was solved.  Anyone else experienced this?

**Comment by lisachenko** [comment]
Hi, try to exclude vendor dir from processing by adding path to the `excludePaths` option for the kernel.

**Comment by yugenekr** [comment]
Hello,
Thank you for the advice about ```excludePaths``` option. 
I had the same error thrown, the issue was fixed updating AspectMock customization according to what's written in README.md
```
* `includePaths` directories with files that should be enhanced by Go Aop. Should point to your applications source files as well as framework files and any libraries you use..
* `excludePaths` a paths in which PHP files should not be affected by aspects. **You should exclude your tests files from interception**.
```

As an example, **in my case** this update gives (written in /tests/bootstrap.php):
```
$kernel = \AspectMock\Kernel::getInstance();
$kernel->init([
	'debug'        => true,
	'includePaths' => [__DIR__.'/../src'],
	'excludePaths' => [__DIR__.'/../']
]);
```

**Comment by individualing** [comment]
hi, do your issue has been solved?  the same problem happens to me

**Comment by loren-osborn** [comment]
I only noticed last night that `"goaop/parser-reflection"` isn't actually included in `composer.json`'s `"require"` property. If adding it resolves the issue, it should be a very simple PR.
