### ISSUE TITLE
AspectMock stopped working for me after upgrading to PHP7

### ISSUE THREAD

**Issue by AyrtonDetex** [Codeception/AspectMock#115]
I have been using AspectMock in my codebase for a couple of months and it has been working well. We decided to upgrade our code to use PHP7, and AspectMock stopped mocking functions. I am hopeful that someone can give me an idea of what I am missing here-

Upgrading from:
- PHP 5.5.38
- Zend Framework 1.10.1
- Codeception 2.2.6
- AspectMock 1.0.0
(And PHPUnit 4.8.27 gets installed through these)

I created some bare bones tests that weren't using anything extra I had made:

The class that I plan to Mock:
```
<?php

class App_Mock_Things {
    
    public function getFive()   {
        return 5;
    }
    
    public static function getSixStatic()  {
        return 6;
    }
}
```

And then the tests
```
<?php

use AspectMock\Test;

use App_Mock_Things as Thing;

class MockTest extends \Codeception\Test\Unit {

    public function testNormal()   {
        $thing = new Thing();
        Test::double($thing, ['getFive' => 3]);
        $this->assertEquals(3, $thing->getFive());
    }

    public function testStatic()   {
        Test::double("App_Mock_Things", ['getSixStatic' => 4]);
        $this->assertEquals(4, Thing::getSixStatic());
    }
}
```

My AspectMock is set up inside of `tests/_bootstrap.php` like so:
```
use \AspectMock\Kernel;

$kernel = Kernel::getInstance();
$kernel->init([
                  'includePaths' => [__DIR__.'/../application'],
                  'excludePaths' => [__DIR__]
              ]);
```

The tests work as they are right now, and then I run the following commands to upgrade to PHP7:
`brew unlink php55`
`brew install php70 --with-homebrew-apxs --with-apache` (This installed 7.0.9)
Then I modified my `httpd.conf` to `LoadModule` php7 instead of php5
`sudo apachectl restart`
At this point if I do a `./codecept run`, I get the following error:
```Fatal error: Uncaught Error: Class 'TokenReflection\Stream\StringStream' not found in application/vendor/andrewsville/php-token-reflection/TokenReflection/Broker.php:165
Stack trace:
#0 application/vendor/codeception/aspect-mock/src/AspectMock/Intercept/BeforeMockTransformer.php(24): TokenReflection\Broker->processString('<?php\n/**\n * PH...', '/Users/astout/w...', true)
#1 application/vendor/goaop/framework/src/Instrument/Transformer/CachingTransformer.php(124): AspectMock\Intercept\BeforeMockTransformer->transform(Object(Go\Instrument\Transformer\StreamMetaData))
#2 application/vendor/goaop/framework/src/Instrument/Transformer/CachingTransformer.php(64): Go\Instrument\Transformer\CachingTransformer->processTransformers(Object(Go\Instrument\Transformer\StreamMetaData))
#3 application/vendor/goaop/framewo in application/vendor/andrewsville/php-token-reflection/TokenReflection/Broker.php on line 165
```

I then upgraded AspectMock to 2.0.0, which I was figuring I'd need to do anyway, and reran composer. After that, I received the error

```
Fatal error: Uncaught Error: Class 'Go\ParserReflection\ReflectionFile' not found in application/vendor/codeception/aspect-mock/src/AspectMock/Intercept/BeforeMockTransformer.php:16
Stack trace:
#0 application/vendor/goaop/framework/src/Instrument/Transformer/CachingTransformer.php(124): AspectMock\Intercept\BeforeMockTransformer->transform(Object(Go\Instrument\Transformer\StreamMetaData))
#1 application/vendor/goaop/framework/src/Instrument/Transformer/CachingTransformer.php(64): Go\Instrument\Transformer\CachingTransformer->processTransformers(Object(Go\Instrument\Transformer\StreamMetaData))
#2 application/vendor/goaop/framework/src/Instrument/ClassLoading/SourceTransformingLoader.php(134): Go\Instrument\Transformer\CachingTransformer->transform(Object(Go\Instrument\Transformer\StreamMetaData))
#3 appli in /Users/astout/workspace/FreeMark-refactored/application/vendor/codeception/aspect-mock/src/AspectMock/Intercept/BeforeMockTransformer.php on line 16
```

Following the suggestion by lisachenko found in another recent open issue, https://github.com/Codeception/AspectMock/issues/112 I excluded my `vendor` directory from the Kernel

```
use \AspectMock\Kernel;

$kernel = Kernel::getInstance();
$kernel->init([
                  'includePaths' => [__DIR__.'/../application'],
                  'excludePaths' => [
                      __DIR__, 
                      __DIR__.'/../application/vendor']
              ]);
```
I ran `./codecept run` again at this point, and all of my tests that don't use AspectMock pass, and all of the tests that do use it fail. AspectMock doesn't seem to be changing any of the values, but it doesn't error.

If anyone has any insight as to what I am missing, it would be appreciated. I would like to get on the PHP7 train as soon as possible, and AspectMock is a tool I don't want to leave behind.

**Comment by nordbergr** [comment]
I occasionally get the Failure for a class not being found when i use phpunit with aspectmock.  The solution I use is to remove everything in the AspectMock cache and run the unit tests again.  For example my AspectMock cache lives in /usr/tmp/aspectmock_cache/ and I use `sudo rm -rf /usr/tmp/aspectmoch_cache/*`.  Some times the unit tests hang towards the end (there are 5500+ unit tests) so I often have to kill the run (ctrl+c) and run again.

**Comment by DavertMik** [comment]
That's why we have AspectMock 2.0 - which is designed for PHP7 purely. Version 1.0 is still available for PHP 5.5-5.6

**Comment by AyrtonDetex** [comment]
Thank you both for your replies.

@nordbergr - I actually was not using a cache directory. I didn't expect it to work, but I tried making one and setting up AspectMock to use it just to see if anything changed, and it didn't.

@DavertMik - I know my post was long (I was trying to be as detailed as possible) but about 3/5ths of the way down I said 

> I then upgraded AspectMock to 2.0.0, which I was figuring I'd need to do anyway, and reran composer. After that, I received the error

I am using AspectMock 2.0 and I still have this issue of AspectMock silently failing to mock my functions. But using AspectMock 1.0 on the same project (with PHP 5.5.38) it works beautifully. So I am fairly sure it is set up properly, unless I need to do something extra for AspectMock 2.0.

**Comment by nordbergr** [comment]
I upgraded to AspectMock 2.0.0 with PHP 7 but now aspect mock is throwing errors in [REgistry.php](https://github.com/Codeception/AspectMock/blob/master/src/AspectMock/Core/Registry.php) with any function call on $mocker.  Not sure if these issues could be related.

**Comment by individualing** [comment]
hi,did your issue has been solved? the same problem happens to me.

**Comment by juanserra** [comment]
@AyrtonDetex I ran into the exact same issue myself, I wonder if you managed to fix it at all? Thanks

**Comment by AyrtonDetex** [comment]
@juanserra I'm afraid not. The project I was having this issue on was put on the back burner so I haven't been looking into it at all (though I had already tried everything I could think of at the time of posting this ticket, so I'm not sure I'd have been successful anyway)

**Comment by juanserra** [comment]
@AyrtonDetex Ah well, thanks for the response anyway! I'll keep trying and will post a solution if I find one. 
I think I already tried everything I could think of, I'm thinking about completely removing AspectMock and replace it with Mockery or similar.

**Comment by AyrtonDetex** [comment]
@juanserra I was feeling the same way. Upgrading to later versions of PHP can't be ignored forever... if I can't make this work when I do eventually go back to this project I'll probably be replacing it with Mockery too.
