### ISSUE TITLE
PHPUnit 6 Support?

### ISSUE THREAD

**Issue by paulrrogers** [Codeception/AspectMock#140]
PHPUnit v6 now uses namespaces, and as of February v5 will be EOL. Any chance AspectMock and Go! AOP will support v6 officially?

**Comment by DavertMik** [comment]
Yeah, it should...

**Comment by DavertMik** [comment]
What parts are not compatible with PHPUnit 6?

**Comment by paulrrogers** [comment]
The change to namespaces ("use PHPUnit\...") from the old underscored convention ("use PHPUnit_...") is one incompatibility.

**Comment by qschmick** [comment]
This would be a great enhancement, biggest changes should be the namespace and then some deprecated APIs (https://thephp.cc/news/2017/02/migrating-to-phpunit-6)

**Comment by DavertMik** [comment]
Ok, updated
