### ISSUE TITLE
AspectMock does fail PHPUnit with no assertions done

### ISSUE THREAD

**Issue by icanhazstring** [Codeception/AspectMock#151]
Currently `verifyInvoked` does not count towards the assertion count of PHPUnit.
This is probably due to the "non integration" of AspectMock into PHPUnit.

I can think of two possible solutions for this (if this is an issue at all)

1. Provide a phpunit-extension combined with AspectMock. This extension could provide a specific `TestCase` class which already does the integration for you (cleaning test mocks and stuff) and giving you the ability to create doubles as well as new asserts

2. Given a trait could work as well. Providing the needed data to create double and check for method invokations, while counting towards the assertion count for PHPUnit while keeping the default `extends TestCase` structure for existing tests

**Comment by icanhazstring** [comment]
@bhoehl yea this could be an option. But it would be nice to actually get the count of the assertions I do with AspectMock.

Maybe i'll find some time to actually provide an extension to invoke AspectMock :)

**Comment by Naktibalda** [comment]
I merged pull request.

**Comment by Naktibalda** [comment]
Released as 3.1.0
