### ISSUE TITLE
AspectMock don't mock DateTime object

### ISSUE THREAD

**Issue by tupikoff** [Codeception/AspectMock#163]
I have a problem with mocking php Datetime object. Does AspectMock work correctly with global php objects?

code
```
$datetime = test::double(DateTime::class, ['format' => '1979-06-18']);
$date = (new DateTime())->format('Y-m-d');
$datetime->verifyInvoked('format');
$this->assertEquals('1979-06-18', $date);
```

will raise
```
Expected DateTime::format to be invoked but it never occurred
```

**Comment by pblwlln** [comment]
I started to use [Chronos](https://github.com/cakephp/chronos) instead of using \DateTime, because I had the same problem trying to mock \DateTime class

**Comment by Naktibalda** [comment]
This is a missing feature of goaop: https://github.com/goaop/framework/issues/188
