### ISSUE TITLE
Status of AspectMock?

### ISSUE THREAD

**Issue by troy-rudolph** [Codeception/AspectMock#191]
I don't mean to give offence in asking these questions.  Nevertheless, I need to ask so our company can decide how to proceed to PHP 7.4 and 8.0.  

Has AspectMock been abandoned?  If not, is there a discussion that I might follow to better understand?

Thank you.

P.S. The question is a general one, but is prompted by https://github.com/Codeception/AspectMock/issues/185.

**Comment by Naktibalda** [comment]
AspectMock isn't actively developed, but it isn't completely abandoned either.

I don't use AspectMock and I don't follow all activity here, but it is part of Codeception organization, so I check what's happening here few times a year and I can merge pull requests, release new versions, fix occassional incompatibility, but it is up to community to fix bugs and implement new features.
