### ISSUE TITLE
Problem mocking Eloquent Methods

### ISSUE THREAD

**Issue by crissi** [Codeception/AspectMock#20]
I am using the popular framework Laravel and I am trying to mock a class named User that extends Eloquent:
I am trying to mock the create-method that is defined on the abstract class that extends the User class.

```
test::double('\Illuminate\Database\Eloquent\Model', ['create' =>  'create' ]);
\User::create([])->shouldReturn('create'); //still hitting the database
```

How come this is not working?

**Comment by macoto-liu** [comment]
@crissi  Could you explain how did you solve it ? I'm having the same issue. In Laravel the model always hit the database when using AspectMock.

**Comment by crissi** [comment]
I don't remember, years since I last used this package, sorry

**Comment by macoto-liu** [comment]
thanks. 

I just manage it works by registering the Eloquent source path in `includePaths` as shown below.

```
$kernel = \AspectMock\Kernel::getInstance();
$kernel->init([
    'debug' => true,
    'cacheDir'  => '/tmp/crm',
    'includePaths' => [
        __DIR__.'/../src',
        __DIR__.'/../vendor/illuminate/database/Eloquent'
    ]
]);
```
