### ISSUE TITLE
Unable to disable caching

### ISSUE THREAD

**Issue by lkysow** [Codeception/AspectMock#47]
Due to https://github.com/Codeception/AspectMock/issues/46 I have attempted to disable caching however this currently doesn't work.

If I don't set `cacheDir` in the config, or even if I set it to `null` it gets overridden here:

```php
// AspectKernel.php
protected function normalizeOptions(array $options)
{
    $options = array_replace($this->getDefaultOptions(), $options);
    ...
    $options['cacheDir'] = PathResolver::realpath($options['cacheDir']);
}
```

When `PathResolver::realpath` gets passed `null` it returns the current directory. A simple change would be to do this instead:

```php
$options['cacheDir'] = $options['cacheDir'] !== null ? PathResolver::realpath($options['cacheDir']) : null;
```

Then when we get to the `CachingTransformer` `$this->cachePath` is always set to something and so it tries to write the cache in an undesired directory:

```php
public function transform(StreamMetaData $metadata)
{
    // Do not create a cache
    if (!$this->cachePath) { // this is never null
        $this->processTransformers($metadata);

        return;
    }
```

**Comment by lisachenko** [comment]
Reported in https://github.com/lisachenko/go-aop-php/issues/181 and fixed for the 0.x and master branches of goaop.

**Comment by lkysow** [comment]
Ahh okay we will upgrade then. Thanks!
