### ISSUE TITLE
Generators result in fatal error

### ISSUE THREAD

**Issue by TiGR** [Codeception/AspectMock#50]
Let's say you have two classes in separate files:

```php
<?php

class GeneratorTest extends GeneratorTestParent {}
```

```php
<?php

class AOPTestParent {
    protected function generator()
    {
        yield 'foo';
    }
}
```

Then, it is being internally converted to:

```php
<?php

class AOPTestParent {
    protected function generator()
    { if (($__am_res = __amock_before($this, __CLASS__, __FUNCTION__, array(), false)) !== __AM_CONTINUE__) return $__am_res; 
        yield 'foo';
    }
}
```

And any inclusion of AOPTest results in `PHP Fatal error:  Generators cannot return values using "return"`, since return was added to that method.

**Comment by Fedott** [comment]
+1

**Comment by wyhw** [comment]
+1

**Comment by iainfogg** [comment]
Also getting the same issue - anyone know if this likely to be resolved? Not sure how I can use AspectMock without that, as it crashes part way through my tests currently.

**Comment by stefandoorn** [comment]
I'm facing the same problem. I could rewrite code not to use generators, but its such a nice feature :)
