### ISSUE TITLE
verifyInvoked always returns "never occur"

### ISSUE THREAD

**Issue by Schizy** [Codeception/AspectMock#57]
Hello,

I tryed this following code :

```php
<?php
namespace Stockholders\Tests\Includes;

use Stockholders\Includes\Controller;
use AspectMock\Test as test;

class ControllerTest extends \PHPUnit_Framework_TestCase
{
    protected function tearDown()
    {
        test::clean(); // remove all registered test doubles
    }

	public function testReturnErrorIfNotValidOrDuplicateCallsMethods()
	{
		$mock = test::double('\Stockholders\Includes\Controller', [
			'returnErrorIfNotValidOrDuplicate'	=> 'mockedReturnValue'
		]);

		\Stockholders\Includes\Controller::returnErrorIfNotValidOrDuplicate();

		$mock->verifyInvoked('returnErrorIfNotValidOrDuplicate');
	}
}
```

But it always returns "never occur", like this :
```console
1) Stockholders\Tests\Includes\ControllerTest::testReturnErrorIfNotValidOrDuplicateCallsMethods
Expected \Stockholders\Includes\Controller::returnErrorIfNotValidOrDuplicate to be invoked but it never occur.

/var/www/bo/vendor/codeception/aspect-mock/src/AspectMock/Proxy/Verifier.php:64
/var/www/bo/sites/all/modules/stockholder_relationship/Tests/Includes/ControllerTest.php:22
```

The weird part is that if i die the method calls, it will return 'mockedReturnValue' like he might be.

Any idea ? I'm really stuck since yersteday...

**Comment by rbellido** [comment]
I think in order for it to work, you have to call `verifyInvoked` first before calling your `returnErrorIfNotValidOrDuplicate` method. Let me know if that works. I currently have the same issue here with "never occur" errors but I am calling `verifyInvoked` first before calling the method I'm trying to test.

**Comment by rbellido** [comment]
ok @Schizy. After wrestling with this error, I found that if you pass in an absolute namespace to `double` the test fails with the 'never occur' error. So try calling `double` without the absolute and see if that works

```php
        $mock = test::double('Stockholders\Includes\Controller', [
            'returnErrorIfNotValidOrDuplicate'  => 'mockedReturnValue'
        ]);
```

**Comment by Schizy** [comment]
Thanks @rbellido ! It works! :)
