### ISSUE TITLE
AspectMock couldn't parse some of files. Try to exclude them from parsing list.

### ISSUE THREAD

**Issue by cornernote** [Codeception/AspectMock#61]
Hello,

The is no doubt something I am doing wrong, but any help would be greatly appreciated.  I get the following error from travis (but not when I run locally):

```
AspectMock couldn't parse some of files.                                     
Try to exclude them from parsing list.                                      
  There were following reasons for this exception:                             
  Function trait_exists was redeclared (previousy declared in file /home/travis/build/bedezign/yii2-audit/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php).  
```

I have tried excluding the `build/` folder (although it's not in the include list) which didnt help.  Here is my config:

https://github.com/bedezign/yii2-audit/blob/codeception-tests/tests/codeception/_bootstrap.php

**Comment by cornernote** [comment]
not to worry, i found how to exclude it correctly

**Comment by tuanvu-se** [comment]
Hi, I got this error, how to fix or exclude from parsing list ?

**Comment by cornernote** [comment]
When I had this issue it was because I had the wrong path.

This is how my `excludePaths` looked when it was working.

```
$kernel = Kernel::getInstance();
$kernel->init([
    'excludePaths' => [__DIR__, VENDOR_DIR . '/phpunit'],
]);
```

**Comment by tuanvu-se** [comment]
Thank you very much, it solved problem. However, I got a new issue here https://github.com/Codeception/AspectMock/issues/85 . Have you ever meet it ?

**Comment by cornernote** [comment]
Sorry, I'm very unfamiliar with AspectMock.  I was only using it because it came with a test suite that I was using.

**Comment by tuanvu-se** [comment]
Thank alot for your kind :)
