### ISSUE TITLE
unexpected 'as' (T_AS) error

### ISSUE THREAD

**Issue by przemekperon** [Codeception/AspectMock#68]
When mocking some class the following code:
```php
foreach (require $file as $key => $value) {
...
}
```

is returning error "PHP Parse error:  syntax error, unexpected 'as' (T_AS)" . It works when not using AspectMock.

**Comment by lisachenko** [comment]
@przemekperon yes, it's wrong detection of `require` boundaries. Try to refactor your code like this:

```php
$config = require $file;
foreach ($config as $key => $value) {
    // ...
}
```

**Comment by przemekperon** [comment]
Thanks for the reply. Unfortunately it's a 3rd party code - I'll pass the suggestion to the package maintainer.
