### ISSUE TITLE
If a parameter is passed with a null value, further parameters won't be passed

### ISSUE THREAD

**Issue by mexxmann** [Codeception/AspectMock#74]
I have the following target method I would like to mock with double():

```
public function leftJoin($table, $alias = NULL, $condition = NULL, $arguments = array()) {
    /// some code
}
```

Then my code under test calls it like this:

```
$someObject->leftJoin('my_table', null, 'some_condition');
```

The $condition parameter will never be passed.

I think it's because of this code from InstanceProxy.php:

```
        for($i = 0; $i < count($params); $i++)
        {
            if(!isset($args[$i]))
            {
                break;
            }
```

**Comment by kenjis** [comment]
It must be a bug.
Should use `array_key_exists()`?

**Comment by kbanman** [comment]
👍  I just ran into this issue as well
