### ISSUE TITLE
I can't mock object in Yii2 

### ISSUE THREAD

**Issue by tuancode** [Codeception/AspectMock#78]
Hi,
I have read the guide and follow to install and set up AspectMock to Yii2 basic. Everything is fine, but it seem to be not actually work, the object is not mocked. I think the issue may be derived from path configuration, but I didn't find the solution. This is my code:

``` php
# tests/codeception/_bootstrap.php
<?php
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'test');

defined('YII_TEST_ENTRY_URL') or define('YII_TEST_ENTRY_URL', parse_url(\Codeception\Configuration::config()['config']['test_entry_url'], PHP_URL_PATH));
defined('YII_TEST_ENTRY_FILE') or define('YII_TEST_ENTRY_FILE', dirname(dirname(__DIR__)) . '/web/index-test.php');

$kernel = \AspectMock\Kernel::getInstance();
$kernel->init([
    'debug' => true,
    'includePaths' => [__DIR__.'/../../'],
]);
$kernel->loadFile(__DIR__ . '/../../vendor/yiisoft/yii2/Yii.php');

require_once(__DIR__ . '/../../vendor/autoload.php');
require_once(__DIR__ . '/../../vendor/yiisoft/yii2/Yii.php');

$_SERVER['SCRIPT_FILENAME'] = YII_TEST_ENTRY_FILE;
$_SERVER['SCRIPT_NAME'] = YII_TEST_ENTRY_URL;
$_SERVER['SERVER_NAME'] = parse_url(\Codeception\Configuration::config()['config']['test_entry_url'], PHP_URL_HOST);
$_SERVER['SERVER_PORT'] =  parse_url(\Codeception\Configuration::config()['config']['test_entry_url'], PHP_URL_PORT) ?: '80';

Yii::setAlias('@tests', dirname(__DIR__));
```

``` php
# test/codeception/models/UserTest.php
<?php
namespace tests\codeception\unit\models;

use yii\codeception\TestCase;
use app\models\User;
use AspectMock\Test as test;

class UserTest extends TestCase
{

    protected function tearDown()
    {
        test::clean(); 
    }
        public function testUserObject()
    {
        $user = test::double(User::className(), [
            'getId' => '5'
        ]);
        $user->getId();
        $user->verifyInvoked('getId');
    }
}
```

This is result

>   [Exception] Called app\models\User->getId, but this is a proxy for a class definition.
> Probably you was trying to access instance method.
> Construct an instance from this class  

Does I make wrong some thing? Please help! Thanks in advance.

**Comment by nevermnd** [comment]
You are including the Yii base class manually after loading it via kernel. Here is my bootstrap file.

```php
<?php
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'test');

defined('YII_TEST_ENTRY_URL') or define('YII_TEST_ENTRY_URL', parse_url(\Codeception\Configuration::config()['config']['test_entry_url'], PHP_URL_PATH));
defined('YII_TEST_ENTRY_FILE') or define('YII_TEST_ENTRY_FILE', dirname(dirname(__DIR__)) . '/web/index-test.php');

// Include autoload before configuring the Kernel
require_once(__DIR__ . '/../../vendor/autoload.php');

// Kernel configuration
$kernel = AspectMock\Kernel::getInstance();
$kernel->init([
    'appDir'       => __DIR__ . '/../..',
    'debug'        => true,
    'includePaths' => [__DIR__ . '/../..'],
]);

// Load additional files via kernel
$kernel->loadFile(__DIR__ . '/../../vendor/yiisoft/yii2/Yii.php');
$kernel->loadFile(__DIR__ . '/../../vendor/yiisoft/yii2/base/UnknownClassException.php');
$kernel->loadFile(__DIR__ . '/../../vendor/yiisoft/yii2/base/ErrorException.php');

$_SERVER['SCRIPT_FILENAME'] = YII_TEST_ENTRY_FILE;
$_SERVER['SCRIPT_NAME'] = YII_TEST_ENTRY_URL;
$_SERVER['SERVER_NAME'] = parse_url(\Codeception\Configuration::config()['config']['test_entry_url'], PHP_URL_HOST);
$_SERVER['SERVER_PORT'] = parse_url(\Codeception\Configuration::config()['config']['test_entry_url'], PHP_URL_PORT) ?: '80';

Yii::setAlias('@tests', dirname(__DIR__));

```

**Comment by wirwolf** [comment]
In AspectMock 2.0 object not mocked
`define('ROOT', dirname(dirname(__DIR__)) . '/');

require_once ROOT . 'vendor/autoload.php';
use Codeception\Configuration;

$kernel = AspectMock\Kernel::getInstance();

$kernel->init([
    'appDir'       => ROOT . 'app/',
    'cacheDir'     => ROOT.'storage/runtime/aspect_mock',
    'debug'        => true,
    'includePaths' => [
        ROOT. 'app/',
        ROOT . 'tests/'
    ],
]);

// Load additional files via kernel
$kernel->loadFile(ROOT . 'vendor/yiisoft/yii2/Yii.php');
$kernel->loadFile(ROOT . 'vendor/yiisoft/yii2/base/UnknownClassException.php');
$kernel->loadFile(ROOT . 'vendor/yiisoft/yii2/base/ErrorException.php');

$env = new Dotenv\Dotenv(ROOT);
$env->load();

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'testing');

defined('YII_TEST_ENTRY_URL') or define(
    'YII_TEST_ENTRY_URL',
    parse_url(Configuration::config()['config']['test_entry_url'], 5)
);
defined('YII_TEST_ENTRY_FILE') or define('YII_TEST_ENTRY_FILE', dirname(dirname(__DIR__)) . '/web/index-test.php');

$_SERVER['SCRIPT_FILENAME'] = YII_TEST_ENTRY_FILE;
$_SERVER['SCRIPT_NAME'] = YII_TEST_ENTRY_URL;
$_SERVER['SERVER_NAME'] = parse_url(Configuration::config()['config']['test_entry_url'], PHP_URL_HOST);
$_SERVER['SERVER_PORT'] = parse_url(Configuration::config()['config']['test_entry_url'], PHP_URL_PORT) ?: '80';



Yii::setAlias('@tests', dirname(__DIR__));`
Project tree

`
├── app
│   ├── Assets
│   │   └── AppAsset.php
│   ├── Components
│   │   ├── Cache.php
│   ├── Controllers
│   │   └── SiteController.php
│   ├── Foo.php
│   ├── Models
│   │   ├── AuthAssignment.php
│   │   ├── AuthItemChild.php
│   │   ├── AuthItem.php
│   │   ├── AuthRule.php
│   │   ├── AuthUserAgents.php
│   │   ├── AuthUser.php
│   │   ├── AuthUserSessions.php
│   │   └── Users.php
│   ├── Modules
│   │   ├── notification
│   │   │   ├── Components
│   │   │   │   ├── AbstractNotificator.php
│   │   │   │   ├── EmailNotificator.php
│   │   │   │   ├── Notificator.php
│   │   │   │   └── PhoneNotificator.php
│   │   │   ├── Exceptions
│   │   │   │   ├── NotificationException.php
│   │   │   │   └── RequireException.php
│   │   │   ├── Models
│   │   │   │   └── NotificationMessages.php
│   │   │   ├── Module.php
│   │   │   └── NotificationService.php
│   └── views
├── composer.json
├── composer.lock
├── composer.phar
├── config
│   └── web
│       ├── components.php
│       ├── modules.php
│       ├── params.php
│       └── web.php
├── database
│   ├── Migrations
│   │   ├── m160530_143249_client_chat_massages.php
│   └── Structure
├── LICENSE.md
├── README.md
├── requirements.php
├── storage
│   ├── runtime
│   │   ├── aspect_mock
│   │   │   └── _annotations
│   └── static
├── tests
│   ├── acceptance.suite.yml
│   ├── _bootstrap.php
│   ├── codeception
│   │   ├── acceptance
│   │   │   ├── AcceptanceTester.php
│   │   │   └── _bootstrap.php
│   │   ├── acceptance.suite.yml
│   │   ├── bin
│   │   │   ├── _bootstrap.php
│   │   │   ├── yii
│   │   │   └── yii.bat
│   │   ├── _bootstrap.php
│   │   ├── config
│   │   │   ├── acceptance.php
│   │   │   ├── config.php
│   │   │   ├── functional.php
│   │   │   └── unit.php
│   │   ├── fixtures
│   │   ├── functional
│   │   │   ├── _bootstrap.php
│   │   ├── templates
│   │   ├── TestCase.php
│   │   ├── unit
│   │   │   ├── _bootstrap.php
│   │   │   ├── modules
│   │   │   │   ├── notification
│   │   │   │   │   └── components
│   │   │   │   │       └── NotificatorTest.php
│   │   │   ├── templates
│   │   │   │   └── fixtures
│   │   │   └── UnitTester.php
│   │   └── unit.suite.yml
│   ├── codeception.yml
│   ├── functional.suite.yml
│   ├── README.md
│   └── unit.suite.yml
├── unpack.sh
├── vendor
`

test:
`    public function testSendNotification() {
        $this->specify(
            'Send email',
            function () {
                $notificator = test::double(EmailNotificator::className(), ['send' => true]);
                $service = new Notificator();
                $args = [
                    'typeId' => 1,
                    'userId' => 2,
                    'initId' => 0,
                    'email' => 'test@gmail.com',
                ];

                $service->setIdentity($args);
                $service->sendNotification();

                $notificator->verifyInvoked('send');
            }
        );
    }`


This is result

> 1) tests\codeception\unit\notification\components\NotificatorTest::testSendNotification
Expected app\Modules\notification\Components\EmailNotificator::send to be invoked but it never occurred. Got:

If i use AspectMock whithout Yii2 all is work.

**Comment by piotr-galas** [comment]
@skiptirengu thank you for this post. It should be included somewher in documentation.
I dig few hours why i get exception after test run and lines:
```
$kernel->loadFile(__DIR__ . '/../../vendor/yiisoft/yii2/base/UnknownClassException.php');
$kernel->loadFile(__DIR__ . '/../../vendor/yiisoft/yii2/base/ErrorException.php');
````
Solve my problem. Thank you so much
