### ISSUE TITLE
How to Override even standard PHP functions in global namespace?

### ISSUE THREAD

**Issue by tarnum777** [Codeception/AspectMock#80]
Documentation says that we can do smth like this:
namespace demo;
\AspectMock\Test::func("demo", 'time', 'now');
$this->assertEquals('now', time());

So is it possible to do same for global namespace, so it will be like:
\AspectMock\Test::func("\", 'time', 'now'); or \AspectMock\Test::func("", 'time', 'now'); 
so calling  time() will return 'now' anywhere after it was mocked, not only inside namespace 'demo' and not only inside test code

**Comment by lisachenko** [comment]
It's impossible to do this on userland level, because this will require special PHP extension.

**Comment by tarnum777** [comment]
But why is this impossible?As a suggestion it would be possible maybe to use smth like runkit_function_redefine and include runkit library via composer?

**Comment by DavertMik** [comment]
We don't support runkit. Sorry.
