### ISSUE TITLE
How do I get class mocking to work with phpunit?

### ISSUE THREAD

**Issue by MPV** [Codeception/AspectMock#84]
Hi, 
I have built a quick and simple example project where I just try to mock code like this:

```
public static function myClassMethod()
{
	return 'always this string';
}
```

I'm expecting to be able to replace what this class method returns, for example by doing something like this with AspectMock in my unit test:

```
// Arrange:
\AspectMock\Test::double('\MyClass', ['myClassMethod' => 'a']);

// Act:
MyClass::myClassMethod();

// Assert:
$this->assertEquals('a', $classMethodReturned);
```

However, this doesn't work in my code. 

1. Can AspectMock do this, or have I misunderstood the project?
2. If it can do it, could it be that I'm setting it up, or using it incorrectly?

You can see the full (hopefully very simple) code here:
https://github.com/MPV/AspectMock-test

When I run the code in the repository, this is the output I get:
```
./vendor/phpunit/phpunit/composer/bin/phpunit test 
PHPUnit 3.7.38 by Sebastian Bergmann.

.F

Time: 82 ms, Memory: 4.75Mb

There was 1 failure:

1) MyClassTest::testMockingClassMethod
Expected \MyClass::myClassMethod to be invoked but it never occur. Got:

/Users/vs/Kod/Ticnet/mnxweb-test-aspect-mock/vendor/codeception/aspect-mock/src/AspectMock/Proxy/Verifier.php:64
/Users/vs/Kod/Ticnet/mnxweb-test-aspect-mock/test/MyClassTest.php:24

FAILURES!
Tests: 2, Assertions: 1, Failures: 1.
```

**Comment by MPV** [comment]
When I read this comment...

> **DavertMik commented on 16 Nov 2015**
Yes. AspectMock (and Go AOP) need to get access to autoloader function and patch it in runtime. So it will replace all require and include in order to load patched files
-- https://github.com/Codeception/AspectMock/issues/42#issuecomment-157176739

...it makes me think that the cause might be that I need to be doing autoloading differently for it to work?

**Comment by MPV** [comment]
I've now changed the code to let the AspectMock kernel do the loading (with `$kernel->loadFile(...)`):
https://github.com/MPV/AspectMock-test/commit/17b37f58d2e1a2f70d9c06eb4153f1763659df45

...but I haven't gotten it to work yet.

**Comment by samsonasik** [comment]
@MPV I created PR to your repo to fix the issue with your path. This issue now close-able ;)

**Comment by samsonasik** [comment]
@MPV please close this, as not an issue
